//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaleriOtomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public Musteriler()
        {
            this.Subelers = new HashSet<Subeler>();
        }
    
        public int MusteriNo { get; set; }
        public string MusteriAdSoyad { get; set; }
        public Nullable<int> MusteriYas { get; set; }
        public Nullable<decimal> MusteriBakiye { get; set; }
    
        public virtual ICollection<Subeler> Subelers { get; set; }
    }
}
